name: Build Release
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build_release:
    name: Build Release
    runs-on: ubuntu-latest
    steps:
      # ADD CURRENT DATE TIME TO ENV
      - name: Setting current date time as envirn variable
        run: echo "date::$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV

      # BASIC SETUP
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '12.x'
          distribution: 'zulu'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Installing dependencies
        run: flutter pub get
      - name: Running tests
        run: flutter test

      # BUILD ANDROID APK
      - name: Building Android Release
        run: flutter build apk --release --target-platform android-arm,android-arm64
      - name: Uploading android APK to the artifacts.
        uses: actions/upload-artifact@v2
        with:
          name: release-${{ github.event.repository.name }}-${{ date }}
          path: build/app/outputs/apk/release/app-release.apk

      - name: Cleaning and re-installing dependencies
        run: flutter clean && flutter pub get

      # BUILD ANDROID APP BUNDLE
      - name: Building Android AppBundle
        run: flutter build appbundle --release
      - name: Uploading android app bundle to the artifacts.
        uses: actions/upload-artifact@v2
        with:
          name: release-${{ github.event.repository.name }}
          path: build/app/outputs/bundle/release/app-release.aab

#      - name: Cleaning and re-installing dependencies
#        run: flutter clean && flutter pub get
#
#      # BUILD IOS RELEASE
#      - name: Building iOS Release
#        run: flutter build ios --release --no-codesign
#      - name: Upload iOS release to the artifacts.
#        uses: actions/upload-artifact@v2
#        with:
#          name: release-${{ github.event.repository.name }}
#          path: path/to/ios/release