name: CI
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build_release:
    name: Build Android and iOS Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '12.x'
          distribution: 'zulu'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Installing dependencies
        run: flutter pub get
      - name: Running tests
        run: flutter test
      - name: Building Android Release
        run: flutter build apk --release --target-platform android-arm,android-arm64
      - name: Upload android release to the artifacts.
        uses: actions/upload-artifact@v2
        with:
          name: release-${{ github.event.repository.name }}
          path: build/app/outputs/apk/release/app-release.apk
      - name: Cleaning and re-installing dependencies
        run: flutter clean && flutter pub get
      - name: Building iOS Release
        run: flutter build ios --release --no-codesign
      - name: Upload iOS release to the artifacts.
        uses: actions/upload-artifact@v2
#        with:
#          name: release-${{ github.event.repository.name }}
#          path: path/to/ios/release