name: CI
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build_android:
    name: Build Android Application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '12.x'
          distribution: 'zulu'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Installing dependencies
        run: flutter pub get
      #      - name: Running tests
      #        run: flutter test
      - name: Building Android Release
        run: flutter build apk --release --target-platform android-arm,android-arm64
      - name: Upload generated file to the artifacts.
        uses: actions/upload-artifact@v2
        with:
          name: release-android
          path: build/app/outputs/apk/release/app-release.apk

  build_ios:
    name: Build iOS Application
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Installing dependencies
        run: flutter pub get
      #      - name: Running tests
      #        run: flutter test
      - name: Building iOS Release
        run: flutter build ios --release --no-codesign
#      - name: Upload generated file to the artifacts.
#        uses: actions/upload-artifact@v2
#        with:
#          name: release-ios
#          path: build/app/outputs